
Browser("Advantage Shopping_2").Page("Advantage Shopping").Link("SpeakersCategory").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("SpeakersCategory")_;_script infofile_;_ZIP::ssf43.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("$129.00").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebElement("$129.00")_;_script infofile_;_ZIP::ssf44.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("WebElement").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebElement("WebElement")_;_script infofile_;_ZIP::ssf45.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebButton("save_to_cart").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebButton("save to cart")_;_script infofile_;_ZIP::ssf46.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").Link("ShoppingCart").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("ShoppingCart")_;_script infofile_;_ZIP::ssf47.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("REMOVE").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebElement("REMOVE")_;_script infofile_;_ZIP::ssf48.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("Your shopping cart is").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("helpLink")_;_script infofile_;_ZIP::ssf50.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("Your shopping cart is").Check CheckPoint("Your shopping cart is empty_2") @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebElement("Your shopping cart is")_;_script infofile_;_ZIP::ssf51.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").Link("Link").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("Link")_;_script infofile_;_ZIP::ssf52.xml_;_
